import { Link, Navigate, Route, Routes } from 'react-router-dom';
import { APP_PACKAGE_VERSION } from './appVersion';
import { useWorkerResource } from './hooks/useWorkerResource';

interface Product { id: string; title: string; availableForSale: boolean; featuredImage?: { url: string; altText?: string | null } | null; priceRange: { minVariantPrice: { amount: string; currencyCode: string } } }

function Layout({ children }: { children: React.ReactNode }) { return <main className="min-h-screen"><header className="border-b border-white/10 bg-black/30"><nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><Link className="text-xl font-black tracking-[0.3em]" to="/">0X</Link><div className="flex gap-5 text-sm text-zinc-300"><Link to="/shop">Shop</Link><Link to="/about">Architecture</Link></div></nav></header>{children}<footer className="mx-auto max-w-6xl px-6 py-8 text-xs text-zinc-500">0x {APP_PACKAGE_VERSION} · Shopify development store · Testnet demo only</footer></main>; }
function Home() { return <section className="mx-auto grid max-w-6xl gap-12 px-6 py-24 lg:grid-cols-[1.3fr_0.7fr]"><div><p className="mb-5 text-sm font-semibold uppercase tracking-[0.2em] text-fuchsia-300">Experimental commerce architecture</p><h1 className="max-w-3xl text-5xl font-black leading-tight md:text-7xl">Wear the signal.<br />Keep the proof.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-zinc-300">A Shopify headless storefront with a Cloudflare Worker payment boundary. The portfolio checkout accepts testnet-only demo transfers, never real funds.</p><Link className="btn mt-10 border-0 bg-fuchsia-500 text-white hover:bg-fuchsia-400" to="/shop">Explore the catalog</Link></div><aside className="rounded-3xl border border-fuchsia-300/30 bg-fuchsia-500/10 p-7"><p className="text-sm font-semibold text-fuchsia-200">Trust boundary</p><ol className="mt-5 space-y-4 text-sm text-zinc-200"><li>01 Shopify owns catalog and cart totals.</li><li>02 Worker owns payment intent state.</li><li>03 Server verifies testnet transfer.</li><li>04 Shopify records a tagged demo order.</li></ol></aside></section>; }
function Shop() { const { data, loading, error } = useWorkerResource<{ products: Product[] }>('/v1/products'); return <section className="mx-auto max-w-6xl px-6 py-14"><h1 className="text-4xl font-bold">Catalog</h1><p className="mt-2 text-zinc-400">Products are supplied by Shopify through the 0x Worker.</p>{loading && <p className="mt-10 text-zinc-400">Loading Shopify catalog…</p>}{error && <div className="alert mt-10 border border-amber-400/40 bg-amber-400/10 text-amber-100"><span>{error.message}</span></div>}<div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{data?.products.map((product) => <article key={product.id} className="overflow-hidden rounded-2xl border border-white/10 bg-black/30"><div className="aspect-square bg-zinc-900">{product.featuredImage && <img className="h-full w-full object-cover" src={product.featuredImage.url} alt={product.featuredImage.altText || product.title} />}</div><div className="p-5"><h2 className="font-semibold">{product.title}</h2><p className="mt-2 text-sm text-zinc-400">{product.priceRange.minVariantPrice.amount} {product.priceRange.minVariantPrice.currencyCode}</p><span className="mt-4 inline-block text-xs text-fuchsia-200">{product.availableForSale ? 'Available in demo catalog' : 'Unavailable'}</span></div></article>)}</div></section>; }
function About() { return <section className="mx-auto max-w-3xl px-6 py-20"><h1 className="text-4xl font-bold">Not a payment gateway</h1><p className="mt-6 leading-8 text-zinc-300">This portfolio uses Shopify for catalog and cart data. Crypto checkout is intentionally disabled until its exact testnet token conversion and confirmation policy are specified, implemented, and tested. It is not Shopify Payments or a Shopify-approved payment method.</p></section>; }
export function App() { return <Layout><Routes><Route path="/" element={<Home />} /><Route path="/shop" element={<Shop />} /><Route path="/about" element={<About />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></Layout>; }
